workspace:
  base: /go
  path: src/github.com/tchaudhry91/nagiosagg

pipeline:
  build:
    image: golang
    commands:
      - make lint
      - make test-short

  docker:
    image: plugins/docker
    when:
      branch: master
    commands:
      - make docker-drone
