workspace:
  base: /go
  path: src/github.com/tchaudhry91/nagiosagg

pipeline:
  build:
    image: golang
    commands:
      - make build

  docker:
    image: plugins/docker
    commands:
      - make docker-drone