# Builder 
FROM    golang:latest as BUILDER
ENV     CGO_ENABLED=0 
RUN     mkdir -p /go/src/github.com/tchaudhry91/nagiosagg
WORKDIR /go/src/github.com/tchaudhry91/nagiosagg
COPY    . .
RUN     make build-amd64


# Final Image
FROM       alpine
RUN        apk update &&\
           apk add --no-cache ca-certificates &&\
           rm -rf /var/cache/apk/*
COPY       --from=BUILDER /go/src/github.com/tchaudhry91/nagiosagg/release/nagios-svc /bin/
ENTRYPOINT [ "/bin/nagios-svc" ]
CMD        [ "-nagios_status_dir /statuses" ]